apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: web-app-dev
 namespace: argocd
spec:
 project: default
 source: 
 repoURL: https://github.com/tamilarasan4/argotest.git
 targetRevision: HEAD
 path: deployment/dev
 destination:
 server: https://kubernetes.default.svc
 namespace: dev
 syncPolicy:
 automated:
 prune: true